library(stats)

# mage R package

# This file regroups functions to:
#   1. Compute p-values for the MIC scores
#   1. Filter the matrix based on a MIC threshold of significance
#   2. Standardize the matrix (using zscore)


#' @title assign_pval
#'
#' @description
#' Assigns p-values to MIC scores
#'
#' @param MIC_scores numeric vector of MIC scores
#' @param nb_cells nb of cells in the gene expression matrix
#'
#' @return
#' Returns a vector of p-values
#'
#' @details
#' Since the p-value of a given MIC score cannot be computed
#' by a simple mathemical function, \code{assigns_pval} reads
#' the p-value table generated by the authors of the MINE
#' statistics (see \url{http://www.exploredata.net/Downloads/P-Value-Tables})
#' at the closest \emph{sample_size} to \emph{nb_cells}.
#'
#' For each \emph{MIC score}, \code{assign_pval} will then
#' retrieve the corresponding p-value from this table.
#'
assign_pval <- function(MIC_scores,
                nb_cells) {
  MIC_scores <- round(MIC_scores, 3);

  # Get indexes of each unique value in the MIC score vector
  # ----------------------------------------------------------------------
  uniq_MIC_scores <- unique(MIC_scores);
  uniq_MIC_scores_ix <- list();
  for(i in 1:length(uniq_MIC_scores)) {
    uniq_MIC_scores_ix[[i]] <- which(MIC_scores == uniq_MIC_scores[i]);
  }

  # Get appropriate pval_tab:
  # sample_size must be as close as possible to nb_cells
  # ----------------------------------------------------------------------
  pval_data <- load(system.file("R/sysdata.rda", package = "mage"));
  closest_sample_size_ix <- which.min(abs(as.integer(sample_size) - nb_cells));
  pval_tab <- pval_tables[[closest_sample_size_ix]];

  # Get the boundaries of the table
  # ----------------------------------------------------------------------
  pval_tab_max_MIC <- pval_tab[1, 1];
  pval_tab_min_MIC <- pval_tab[nrow(pval_tab), 1];
  most_signif_MIC_ix <- which(uniq_MIC_scores > c(pval_tab_max_MIC));
  least_signif_MIC_ix <- which(uniq_MIC_scores < c(pval_tab_min_MIC));

  # Get the p-value assigned to any MIC written in pval_tab
  # ----------------------------------------------------------------------
  pval_tab_MIC_scores <- round(pval_tab[,1], 3);
  pval_tab_uniq_MIC_scores <- unique(pval_tab_MIC_scores);
  pval_tab_uniq_MIC_scores_pval <- rep(0, length(pval_tab_uniq_MIC_scores));
  for(i in 1:length(pval_tab_uniq_MIC_scores)) {
    pval_tab_uniq_MIC_scores_pval[i] <-
      round(pval_tab[which(pval_tab_MIC_scores == pval_tab_uniq_MIC_scores[i])[1], 2], 3);
  }
  pval_tab_uniq_MIC_scores_pval <- unlist(pval_tab_uniq_MIC_scores_pval);

  # Use these references to assign a p-value to each MIC score
  # present in the MIC_scores vector
  # ----------------------------------------------------------------------
  p_values <- rep(1, length(MIC_scores)); # Any unassigned MIC will have a p-value of 1
  first_i = length(most_signif_MIC_ix) + 1;
  last_i = length(uniq_MIC_scores) - length(least_signif_MIC_ix) + 1;
  for(i in first_i:last_i) {
    cur_ix <- which.min(
      abs(pval_tab_uniq_MIC_scores
          - uniq_MIC_scores[i]));
    p_values[uniq_MIC_scores_ix[[i]]] <- pval_tab_uniq_MIC_scores_pval[cur_ix];
  }

  # Assign p-value = 0 to any MIC > max(MIC) present in pval_tab
  # ----------------------------------------------------------------------
  for(i in 1:length(most_signif_MIC_ix)) {
    p_values[uniq_MIC_scores_ix[[most_signif_MIC_ix[i]]]] <- 0;
  }

  return(p_values);
}

#' @title adjust_pval
#'
#' @description
#' Adjust p-values using FDR method (Benjamini & Hochberg, 1995)
#'
#' @param pval numeric vector of p-values
#'
#' @return
#' Returns a vector of adjusted p-values
#'
adjust_pval <- function(pval) {
  adjusted_p_values <- p.adjust(p_values, method = "BH");
  return(adjusted_p_values);
}

#' @title filter_scores
#'
#' @description
#' Filter table of scores based on a threshold of significance defined either by a MIC score, or by a p-value
#'
#' @param x data.frame, table of scores
#' @param on variable used for the threshold (set to either \code{"MIC"} or \code{"pval"})
#' @param pval numeric vector of p-values (only if \code{on = "pval"})
#' @param threshold value of the threshold
#'
#' @return
#' Returns a filtered table of scores
#'
filter_scores <- function(x,
                   on = 'MIC',
                   pval = NULL,
                   threshold = 0.4) {

}


file <- "/media/charles/Seagate Expansion Drive/Curie/Analyses/Analyses_CDD/MAGE/A471/794_remaining_mvg/794vg_Mage_out/1-Association_Scores/0-scores.csv";
data <- fread(file, sep = ",", header = T);
MIC_scores <- data[,3][[1]];
nb_cells <- 96;


